services:
  fhir-server:
    image: "samply/blaze:0.30"
    environment:
      BASE_URL: "http://fhir-server:8080"
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      LOG_LEVEL: "debug"
      ENFORCE_REFERENTIAL_INTEGRITY: false
    ports:
      - "8082:8080"
    volumes:
      - "data-store-data:/app/data"
  fhir-data-evaluator:
    image: fhir-data-evaluator
    environment:
      CONVERT_TO_CSV: ${FDE_CONVERT_TO_CSV:-true}
      FHIR_SERVER: "http://fhir-server:8080/fhir"
    volumes:
      - "${FDE_INPUT_MEASURE:-../Documentation/example-measures/example-measure-kds.json}:/app/measure.json"
      - "${FDE_OUTPUT_DIR:-../output}:/app/output"

volumes:
  data-store-data:
