services:
  fhir-server:
    image: "samply/blaze:0.30"
    environment:
      BASE_URL: "http://fhir-server:8080"
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      LOG_LEVEL: "debug"
      ENFORCE_REFERENTIAL_INTEGRITY: false
    ports:
      - "8082:8080"
    volumes:
      - "data-store-data:/app/data"
  fhir-data-evaluator:
    image: fhir-data-evaluator
    environment:
      FHIR_SOURCE_SERVER: "http://fhir-server:8080/fhir"
      FHIR_REPORT_SERVER: "http://fhir-server:8080/fhir"
      SEND_REPORT_TO_SERVER: ${FDE_SEND_REPORT_TO_SERVER:-false}
      AUTHOR_IDENTIFIER_SYSTEM: ${FDE_AUTHOR_IDENTIFIER_SYSTEM:-}
      AUTHOR_IDENTIFIER_VALUE: ${FDE_AUTHOR_IDENTIFIER_VALUE:-}
      PROJECT_IDENTIFIER_SYSTEM: ${FDE_PROJECT_IDENTIFIER_SYSTEM:-}
      PROJECT_IDENTIFIER_VALUE: ${FDE_PROJECT_IDENTIFIER_VALUE:-}
    volumes:
      - "${FDE_INPUT_MEASURE:-../Documentation/example-measures/example-measure-kds.json}:/app/measure.json"
      - "${FDE_OUTPUT_DIR:-../output}:/app/output"
  curl-tester: # dummy container from which curl can request data within the same network as the other containers
    build: .
    entrypoint: ["tail", "-f", "/dev/null"]
    command: ""

volumes:
  data-store-data:
