fhir:
  server: ${FHIR_SERVER}
  user: ''
  password: ''
  maxConnections: ${FLARE_FHIR_MAX_CONNECTIONS:4}
  maxQueueSize: ${FLARE_FHIR_MAX_QUEUE_SIZE:500}
  pageCount: ${FLARE_FHIR_PAGE_COUNT:1000}
measureFile: ${MEASURE_FILE}
