services:
  fhir-server:
    image: "samply/blaze:0.30"
    environment:
      BASE_URL: "http://fhir-server:8080"
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      LOG_LEVEL: "debug"
      ENFORCE_REFERENTIAL_INTEGRITY: false
    ports:
      - "8082:8080"
    volumes:
      - "data-store-data:/app/data"
  proxy:
    image: "nginx:1.27.0"
    ports:
      - "8083:8080"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./proxy.htpasswd:/etc/auth/.htpasswd"
  fhir-data-evaluator:
    image: fhir-data-evaluator
    environment:
      FHIR_SOURCE_SERVER: "http://proxy:8080/fhir"
      FHIR_SOURCE_USER: "test"
      FHIR_SOURCE_PASSWORD: "bar"
      FHIR_REPORT_SERVER: "http://proxy:8080/fhir"
      FHIR_REPORT_USER: "test"
      FHIR_REPORT_PASSWORD: "bar"
      SEND_REPORT_TO_SERVER: ${FDE_SEND_REPORT_TO_SERVER:-false}
      AUTHOR_IDENTIFIER_SYSTEM: ${FDE_AUTHOR_IDENTIFIER_SYSTEM:-}
      AUTHOR_IDENTIFIER_VALUE: ${FDE_AUTHOR_IDENTIFIER_VALUE:-}
      PROJECT_IDENTIFIER_SYSTEM: ${FDE_PROJECT_IDENTIFIER_SYSTEM:-}
      PROJECT_IDENTIFIER_VALUE: ${FDE_PROJECT_IDENTIFIER_VALUE:-}
      PROJECT_IDENTIFIER_SYSTEM_OBFUSCATED_REPORT: ${FDE_PROJECT_IDENTIFIER_SYSTEM_OBFUSCATED_REPORT:-}
      PROJECT_IDENTIFIER_VALUE_OBFUSCATED_REPORT: ${FDE_PROJECT_IDENTIFIER_VALUE_OBFUSCATED_REPORT:-}
      CREATE_OBFUSCATED_REPORT: ${FDE_CREATE_OBFUSCATED_REPORT:-false}
    volumes:
      - "${FDE_INPUT_MEASURE:-../Documentation/example-measures/example-measure-kds.json}:/app/measure.json"
      - "${FDE_OUTPUT_DIR:-../output}:/app/output"
  curl-tester: # dummy container from which curl can request data within the same network as the other containers
    build: .
    entrypoint: [ "tail", "-f", "/dev/null" ]
    command: ""
volumes:
  data-store-data:
